<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Most-commonly-used-numpy-functions" data-toc-modified-id="Most-commonly-used-numpy-functions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Most commonly used numpy functions</a></span><ul class="toc-item"><li><span><a href="#Get-version-of-numpy" data-toc-modified-id="Get-version-of-numpy-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Get version of numpy</a></span></li><li><span><a href="#Supported-functions" data-toc-modified-id="Supported-functions-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Supported functions</a></span></li><li><span><a href="#create-an-array" data-toc-modified-id="create-an-array-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>create an array</a></span></li><li><span><a href="#with-specific-data-type" data-toc-modified-id="with-specific-data-type-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>with specific data type</a></span></li><li><span><a href="#Get-various-attributes" data-toc-modified-id="Get-various-attributes-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Get various attributes</a></span></li><li><span><a href="#Genearate-an-array-based-on-range-values" data-toc-modified-id="Genearate-an-array-based-on-range-values-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Genearate an array based on range values</a></span></li><li><span><a href="#Convert-a-list-into-numpy-array" data-toc-modified-id="Convert-a-list-into-numpy-array-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Convert a list into numpy array</a></span></li><li><span><a href="#or-using-asarray-method" data-toc-modified-id="or-using-asarray-method-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>or using asarray method</a></span></li><li><span><a href="#Generate-random-number" data-toc-modified-id="Generate-random-number-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Generate random number</a></span></li><li><span><a href="#Reshaping-an-array-to-1-D,-2-D,3-D,-N-D" data-toc-modified-id="Reshaping-an-array-to-1-D,-2-D,3-D,-N-D-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Reshaping an array to 1-D, 2-D,3-D, N-D</a></span><ul class="toc-item"><li><span><a href="#1-D" data-toc-modified-id="1-D-1.10.1"><span class="toc-item-num">1.10.1&nbsp;&nbsp;</span>1-D</a></span></li><li><span><a href="#2-D" data-toc-modified-id="2-D-1.10.2"><span class="toc-item-num">1.10.2&nbsp;&nbsp;</span>2-D</a></span></li><li><span><a href="#3-D" data-toc-modified-id="3-D-1.10.3"><span class="toc-item-num">1.10.3&nbsp;&nbsp;</span>3-D</a></span></li><li><span><a href="#4-D" data-toc-modified-id="4-D-1.10.4"><span class="toc-item-num">1.10.4&nbsp;&nbsp;</span>4-D</a></span></li></ul></li><li><span><a href="#Creating-array-of-string" data-toc-modified-id="Creating-array-of-string-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Creating array of string</a></span></li><li><span><a href="#Creating-array-of-string-with-other-data-types" data-toc-modified-id="Creating-array-of-string-with-other-data-types-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Creating array of string with other data types</a></span></li><li><span><a href="#Manipulating-one-element-of-an-array-and-its-impact-on-other-element" data-toc-modified-id="Manipulating-one-element-of-an-array-and-its-impact-on-other-element-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Manipulating one element of an array and its impact on other element</a></span></li><li><span><a href="#create-linearly-spaced-values" data-toc-modified-id="create-linearly-spaced-values-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>create linearly spaced values</a></span></li><li><span><a href="#create-logrithmic-spaced-values" data-toc-modified-id="create-logrithmic-spaced-values-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>create logrithmic spaced values</a></span></li><li><span><a href="#Creating-specific-type-of-array" data-toc-modified-id="Creating-specific-type-of-array-1.16"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>Creating specific type of array</a></span><ul class="toc-item"><li><span><a href="#zeros" data-toc-modified-id="zeros-1.16.1"><span class="toc-item-num">1.16.1&nbsp;&nbsp;</span>zeros</a></span></li><li><span><a href="#ones" data-toc-modified-id="ones-1.16.2"><span class="toc-item-num">1.16.2&nbsp;&nbsp;</span>ones</a></span></li><li><span><a href="#identity" data-toc-modified-id="identity-1.16.3"><span class="toc-item-num">1.16.3&nbsp;&nbsp;</span>identity</a></span></li><li><span><a href="#eye" data-toc-modified-id="eye-1.16.4"><span class="toc-item-num">1.16.4&nbsp;&nbsp;</span>eye</a></span></li><li><span><a href="#empty" data-toc-modified-id="empty-1.16.5"><span class="toc-item-num">1.16.5&nbsp;&nbsp;</span>empty</a></span></li></ul></li><li><span><a href="#Transposing-an-Array" data-toc-modified-id="Transposing-an-Array-1.17"><span class="toc-item-num">1.17&nbsp;&nbsp;</span>Transposing an Array</a></span></li><li><span><a href="#Modifying-array-values" data-toc-modified-id="Modifying-array-values-1.18"><span class="toc-item-num">1.18&nbsp;&nbsp;</span>Modifying array values</a></span></li><li><span><a href="#Spliting-an-array" data-toc-modified-id="Spliting-an-array-1.19"><span class="toc-item-num">1.19&nbsp;&nbsp;</span>Spliting an array</a></span><ul class="toc-item"><li><span><a href="#hsplit--->-Left-to-right-columns" data-toc-modified-id="hsplit--->-Left-to-right-columns-1.19.1"><span class="toc-item-num">1.19.1&nbsp;&nbsp;</span>hsplit --&gt; Left to right columns</a></span></li><li><span><a href="#vsplit--->-Top-to-Bottom-rows" data-toc-modified-id="vsplit--->-Top-to-Bottom-rows-1.19.2"><span class="toc-item-num">1.19.2&nbsp;&nbsp;</span>vsplit --&gt; Top to Bottom rows</a></span></li></ul></li><li><span><a href="#Stacking-up-arrays" data-toc-modified-id="Stacking-up-arrays-1.20"><span class="toc-item-num">1.20&nbsp;&nbsp;</span>Stacking up arrays</a></span><ul class="toc-item"><li><span><a href="#hstack--->-Left-to-right-columns" data-toc-modified-id="hstack--->-Left-to-right-columns-1.20.1"><span class="toc-item-num">1.20.1&nbsp;&nbsp;</span>hstack --&gt; Left to right columns</a></span></li><li><span><a href="#vstack--->-Top-to-Bottom-columns" data-toc-modified-id="vstack--->-Top-to-Bottom-columns-1.20.2"><span class="toc-item-num">1.20.2&nbsp;&nbsp;</span>vstack --&gt; Top to Bottom columns</a></span></li></ul></li><li><span><a href="#Flattening-an-array" data-toc-modified-id="Flattening-an-array-1.21"><span class="toc-item-num">1.21&nbsp;&nbsp;</span>Flattening an array</a></span></li><li><span><a href="#Repeat-and-tile" data-toc-modified-id="Repeat-and-tile-1.22"><span class="toc-item-num">1.22&nbsp;&nbsp;</span>Repeat and tile</a></span><ul class="toc-item"><li><span><a href="#repeat" data-toc-modified-id="repeat-1.22.1"><span class="toc-item-num">1.22.1&nbsp;&nbsp;</span>repeat</a></span></li><li><span><a href="#tile" data-toc-modified-id="tile-1.22.2"><span class="toc-item-num">1.22.2&nbsp;&nbsp;</span>tile</a></span></li></ul></li><li><span><a href="#Append,-Insert,-Concatenate" data-toc-modified-id="Append,-Insert,-Concatenate-1.23"><span class="toc-item-num">1.23&nbsp;&nbsp;</span>Append, Insert, Concatenate</a></span><ul class="toc-item"><li><span><a href="#Append" data-toc-modified-id="Append-1.23.1"><span class="toc-item-num">1.23.1&nbsp;&nbsp;</span>Append</a></span></li><li><span><a href="#Insert" data-toc-modified-id="Insert-1.23.2"><span class="toc-item-num">1.23.2&nbsp;&nbsp;</span>Insert</a></span></li><li><span><a href="#Concatenate" data-toc-modified-id="Concatenate-1.23.3"><span class="toc-item-num">1.23.3&nbsp;&nbsp;</span>Concatenate</a></span></li></ul></li><li><span><a href="#Arithmetic-Operation-on-array" data-toc-modified-id="Arithmetic-Operation-on-array-1.24"><span class="toc-item-num">1.24&nbsp;&nbsp;</span>Arithmetic Operation on array</a></span></li><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-1.25"><span class="toc-item-num">1.25&nbsp;&nbsp;</span>Indexing and Slicing</a></span></li><li><span><a href="#Statistical-functions" data-toc-modified-id="Statistical-functions-1.26"><span class="toc-item-num">1.26&nbsp;&nbsp;</span>Statistical functions</a></span><ul class="toc-item"><li><span><a href="#min,max,argmin,argmax,amin,amix" data-toc-modified-id="min,max,argmin,argmax,amin,amix-1.26.1"><span class="toc-item-num">1.26.1&nbsp;&nbsp;</span>min,max,argmin,argmax,amin,amix</a></span></li><li><span><a href="#Using-axis" data-toc-modified-id="Using-axis-1.26.2"><span class="toc-item-num">1.26.2&nbsp;&nbsp;</span>Using axis</a></span></li><li><span><a href="#mean,median,std,var" data-toc-modified-id="mean,median,std,var-1.26.3"><span class="toc-item-num">1.26.3&nbsp;&nbsp;</span>mean,median,std,var</a></span></li><li><span><a href="#ptp" data-toc-modified-id="ptp-1.26.4"><span class="toc-item-num">1.26.4&nbsp;&nbsp;</span>ptp</a></span></li><li><span><a href="#percentile" data-toc-modified-id="percentile-1.26.5"><span class="toc-item-num">1.26.5&nbsp;&nbsp;</span>percentile</a></span></li><li><span><a href="#Histogram" data-toc-modified-id="Histogram-1.26.6"><span class="toc-item-num">1.26.6&nbsp;&nbsp;</span>Histogram</a></span></li></ul></li><li><span><a href="#Conditional-functions" data-toc-modified-id="Conditional-functions-1.27"><span class="toc-item-num">1.27&nbsp;&nbsp;</span>Conditional functions</a></span><ul class="toc-item"><li><span><a href="#using-where" data-toc-modified-id="using-where-1.27.1"><span class="toc-item-num">1.27.1&nbsp;&nbsp;</span>using where</a></span></li><li><span><a href="#using-nonzero" data-toc-modified-id="using-nonzero-1.27.2"><span class="toc-item-num">1.27.2&nbsp;&nbsp;</span>using nonzero</a></span></li><li><span><a href="#ptp" data-toc-modified-id="ptp-1.27.3"><span class="toc-item-num">1.27.3&nbsp;&nbsp;</span>ptp</a></span></li><li><span><a href="#percentile" data-toc-modified-id="percentile-1.27.4"><span class="toc-item-num">1.27.4&nbsp;&nbsp;</span>percentile</a></span></li><li><span><a href="#using-extract" data-toc-modified-id="using-extract-1.27.5"><span class="toc-item-num">1.27.5&nbsp;&nbsp;</span>using extract</a></span></li></ul></li><li><span><a href="#shallow-copy-and-Deep-copy" data-toc-modified-id="shallow-copy-and-Deep-copy-1.28"><span class="toc-item-num">1.28&nbsp;&nbsp;</span>shallow copy and Deep copy</a></span><ul class="toc-item"><li><span><a href="#shallow-copy-:-modifying-array-'b'-will-be-reflected-in-array-a-as-well" data-toc-modified-id="shallow-copy-:-modifying-array-'b'-will-be-reflected-in-array-a-as-well-1.28.1"><span class="toc-item-num">1.28.1&nbsp;&nbsp;</span>shallow copy : modifying array 'b' will be reflected in array <code>a</code> as well</a></span></li><li><span><a href="#deep-copy-:-modifying-array-'b'-will-NOT-be-reflected-in-array-a" data-toc-modified-id="deep-copy-:-modifying-array-'b'-will-NOT-be-reflected-in-array-a-1.28.2"><span class="toc-item-num">1.28.2&nbsp;&nbsp;</span>deep copy : modifying array 'b' will <code>NOT</code> be reflected in array <code>a</code></a></span></li></ul></li><li><span><a href="#Arithmetic-Operation-on-array" data-toc-modified-id="Arithmetic-Operation-on-array-1.29"><span class="toc-item-num">1.29&nbsp;&nbsp;</span>Arithmetic Operation on array</a></span></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-1.30"><span class="toc-item-num">1.30&nbsp;&nbsp;</span>Linear Algebra</a></span><ul class="toc-item"><li><span><a href="#dot-product" data-toc-modified-id="dot-product-1.30.1"><span class="toc-item-num">1.30.1&nbsp;&nbsp;</span>dot product</a></span></li><li><span><a href="#eigen-values-and-eigen-vectors" data-toc-modified-id="eigen-values-and-eigen-vectors-1.30.2"><span class="toc-item-num">1.30.2&nbsp;&nbsp;</span>eigen values and eigen vectors</a></span></li><li><span><a href="#determinant" data-toc-modified-id="determinant-1.30.3"><span class="toc-item-num">1.30.3&nbsp;&nbsp;</span>determinant</a></span></li><li><span><a href="#inverse-of-a-matrix" data-toc-modified-id="inverse-of-a-matrix-1.30.4"><span class="toc-item-num">1.30.4&nbsp;&nbsp;</span>inverse of a matrix</a></span></li></ul></li><li><span><a href="#Ploynomial-equation" data-toc-modified-id="Ploynomial-equation-1.31"><span class="toc-item-num">1.31&nbsp;&nbsp;</span>Ploynomial equation</a></span></li><li><span><a href="#Get-sin/cos-values-and-plot-them" data-toc-modified-id="Get-sin/cos-values-and-plot-them-1.32"><span class="toc-item-num">1.32&nbsp;&nbsp;</span>Get sin/cos values and plot them</a></span></li><li><span><a href="#Input/Output-in-numpy" data-toc-modified-id="Input/Output-in-numpy-1.33"><span class="toc-item-num">1.33&nbsp;&nbsp;</span>Input/Output in numpy</a></span><ul class="toc-item"><li><span><a href="#saving-in-binary-format" data-toc-modified-id="saving-in-binary-format-1.33.1"><span class="toc-item-num">1.33.1&nbsp;&nbsp;</span>saving in binary format</a></span></li><li><span><a href="#saving-in-binary-format" data-toc-modified-id="saving-in-binary-format-1.33.2"><span class="toc-item-num">1.33.2&nbsp;&nbsp;</span>saving in binary format</a></span></li></ul></li><li><span><a href="#finding-null,-non-null,-nan-values-in-array" data-toc-modified-id="finding-null,-non-null,-nan-values-in-array-1.34"><span class="toc-item-num">1.34&nbsp;&nbsp;</span>finding null, non-null, nan values in array</a></span></li><li><span><a href="#How-to-find-total-number-of-null-values" data-toc-modified-id="How-to-find-total-number-of-null-values-1.35"><span class="toc-item-num">1.35&nbsp;&nbsp;</span>How to find total number of null values</a></span></li></ul></li><li><span><a href="#Interview-Questions" data-toc-modified-id="Interview-Questions-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Interview Questions</a></span></li></ul></div>

# Most commonly used numpy functions

In [1]:
import numpy as np
np

<module 'numpy' from '/Users/pankajkumarsoni/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

## Get version of numpy

In [2]:
np.__version__

'1.21.2'

## Supported functions

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [4]:
len(dir(np))

612

## create an array

In [6]:
a = np.array([])
a

array([], dtype=float64)

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [9]:
l = [1,2,3,4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [11]:
t = (1,2,3,4)
a = np.array(t)
a

array([1, 2, 3, 4])

## with specific data type

In [12]:
a = np.array([1,2,3,4],dtype="int8")
a

array([1, 2, 3, 4], dtype=int8)

## Get various attributes

In [42]:
a = np.array([1,2,3,4,5],dtype="int8")
print(a)
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.ndim)
print(a.flags) # numebr if dimesnions
                # C_CONTIGUOUS (C): The data is in a single, C-style contiguous segment
                # F_CONTIGUOUS (F):The data is in a single, Fortran-style contiguous segment
                # OWNDATA (O): The array owns the memory it uses or borrows it from another object
                # WRITEABLE (W): The data area can be written to. Setting this to False locks the data, making it read-only
                # ALIGNED (A): The data and all elements are aligned appropriately for the hardware
                # UPDATEIFCOPY (U): This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array


[1 2 3 4 5]
int8
5
1
1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



## Genearate an array based on range values

In [16]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [18]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [19]:
a = np.arange(0,10,2,dtype="int16")
a

array([0, 2, 4, 6, 8], dtype=int16)

## Convert a list into numpy array

In [20]:
l = [1,2,3,4]
print(type(l))
a = np.array(l)
print(a)
print(type(a))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


## or using asarray method

In [21]:
l = [1,2,3,4]
b = np.asarray(l)
b

array([1, 2, 3, 4])

In [22]:
l = [1,2,3,4]
b = np.asarray(l,dtype="int32")
b

array([1, 2, 3, 4], dtype=int32)

## Generate random number

In [28]:
a = np.random.randint(1,10)
a

6

In [30]:
a = np.random.randint(1,10,5)
a

array([7, 4, 8, 9, 4])

In [31]:
a = np.random.randint(1,7,10)
a

array([3, 5, 1, 3, 5, 5, 2, 1, 6, 6])

In [32]:
a = np.random.randint(1,7,100)
a

array([1, 2, 4, 2, 6, 2, 6, 1, 5, 4, 3, 1, 2, 3, 2, 3, 1, 2, 4, 3, 2, 1,
       2, 2, 6, 1, 1, 2, 4, 2, 4, 5, 5, 4, 1, 5, 6, 4, 5, 6, 6, 4, 5, 5,
       2, 5, 4, 4, 3, 1, 5, 2, 3, 1, 6, 5, 4, 2, 1, 3, 3, 6, 3, 4, 1, 6,
       6, 5, 5, 5, 1, 5, 1, 5, 3, 1, 1, 5, 5, 5, 3, 5, 4, 2, 1, 3, 6, 1,
       2, 4, 3, 6, 2, 4, 6, 1, 1, 5, 1, 2])

In [33]:
a = np.random.random()
a

0.6431004848153451

In [34]:
a = np.random.random(5)
a

array([0.19136791, 0.59625317, 0.5120028 , 0.42626541, 0.98473554])

In [38]:
a = np.random.rand(5,5)
a

array([[0.67002556, 0.77974936, 0.92980866, 0.77201681, 0.38884319],
       [0.38705028, 0.88391457, 0.04326781, 0.83420853, 0.45918097],
       [0.22329833, 0.27417325, 0.33727581, 0.99818143, 0.27579122],
       [0.44236814, 0.11279955, 0.5588784 , 0.79058595, 0.81895319],
       [0.58569411, 0.53396272, 0.52393269, 0.46347933, 0.24795579]])

## Reshaping an array to 1-D, 2-D,3-D, N-D

### 1-D

In [65]:
a = np.random.randint(1,50,16)
print(a)
print(a.ndim)

[48 29 41 16  4 23 33 16 13 16  6 45 46 32 41 44]
1


### 2-D

In [66]:
a.reshape((4,4)) # default is C

array([[48, 29, 41, 16],
       [ 4, 23, 33, 16],
       [13, 16,  6, 45],
       [46, 32, 41, 44]])

In [67]:
a.reshape((4,4),order="F")

array([[48,  4, 13, 46],
       [29, 23, 16, 32],
       [41, 33,  6, 41],
       [16, 16, 45, 44]])

In [68]:
a.reshape((2,8)) # default is C

array([[48, 29, 41, 16,  4, 23, 33, 16],
       [13, 16,  6, 45, 46, 32, 41, 44]])

In [69]:
b = a.reshape((8,2)) # default is C
b

array([[48, 29],
       [41, 16],
       [ 4, 23],
       [33, 16],
       [13, 16],
       [ 6, 45],
       [46, 32],
       [41, 44]])

In [70]:
b.shape

(8, 2)

In [71]:
b.ndim

2

### 3-D

In [54]:
a = np.random.randint(1,20,27)
print(a)
print(a.ndim)

[ 5 17  1  3 14  8  6  4  7 10 15 10 14 13 10 12 17  2 11  7  4  4  2  3
 17  7 12]
1


In [56]:
b = a.reshape(3,3,3)
b

array([[[ 5, 17,  1],
        [ 3, 14,  8],
        [ 6,  4,  7]],

       [[10, 15, 10],
        [14, 13, 10],
        [12, 17,  2]],

       [[11,  7,  4],
        [ 4,  2,  3],
        [17,  7, 12]]])

In [58]:
b.shape

(3, 3, 3)

In [59]:
b.ndim

3

### 4-D

In [72]:
a = np.random.randint(1,20,81)
print(a)
print(a.ndim)

[12 15  5  1 12  8 13 16  8  5 10  9  4 17  8  3  9  4  5  1 13 19 17  6
  8  7  1  5 11  1  7 11 13 14 15 19  8 10 16  7 12 13 19  3  7 16 18  4
 17 18  6  4 12  2  3 10  7  3  2 16  2 14  5 17  8 15 15 10  3 16 11 17
  1 17 16 11 19  5  6 12 13]
1


In [73]:
b = a.reshape(3,3,3,3)
b

array([[[[12, 15,  5],
         [ 1, 12,  8],
         [13, 16,  8]],

        [[ 5, 10,  9],
         [ 4, 17,  8],
         [ 3,  9,  4]],

        [[ 5,  1, 13],
         [19, 17,  6],
         [ 8,  7,  1]]],


       [[[ 5, 11,  1],
         [ 7, 11, 13],
         [14, 15, 19]],

        [[ 8, 10, 16],
         [ 7, 12, 13],
         [19,  3,  7]],

        [[16, 18,  4],
         [17, 18,  6],
         [ 4, 12,  2]]],


       [[[ 3, 10,  7],
         [ 3,  2, 16],
         [ 2, 14,  5]],

        [[17,  8, 15],
         [15, 10,  3],
         [16, 11, 17]],

        [[ 1, 17, 16],
         [11, 19,  5],
         [ 6, 12, 13]]]])

In [74]:
b.shape

(3, 3, 3, 3)

In [75]:
b.ndim

4

## Creating array of string 

In [2]:
a = np.array(["A","B","C","D"])
a

array(['A', 'B', 'C', 'D'], dtype='<U1')

## Creating array of string with other data types

In [3]:
a = np.array([1,2,3,"A","B","C","D"])
a

array(['1', '2', '3', 'A', 'B', 'C', 'D'], dtype='<U21')

In [5]:
a = np.array([1,2,3,"ABCDE","B","C","D"],dtype="U3")
a

array(['1', '2', '3', 'ABC', 'B', 'C', 'D'], dtype='<U3')

In [7]:
a = np.array([1,2,3,"ABCDE","B","C","D"],dtype=">U3")
a

array(['1', '2', '3', 'ABC', 'B', 'C', 'D'], dtype='>U3')

## Manipulating one element of an array and its impact on other element

In [6]:
a = np.array([1,2,3.5,"ABCDE","B","C","D"],dtype="U3")
a

array(['1', '2', '3.5', 'ABC', 'B', 'C', 'D'], dtype='<U3')

## create linearly spaced values

In [8]:
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [9]:
a = np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [10]:
a = np.linspace(1,10,15,endpoint=False)
a

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
       8.8, 9.4])

## create logrithmic spaced values

In [11]:
a = np.logspace(1,10,15,endpoint=False)
a

array([1.00000000e+01, 3.98107171e+01, 1.58489319e+02, 6.30957344e+02,
       2.51188643e+03, 1.00000000e+04, 3.98107171e+04, 1.58489319e+05,
       6.30957344e+05, 2.51188643e+06, 1.00000000e+07, 3.98107171e+07,
       1.58489319e+08, 6.30957344e+08, 2.51188643e+09])

## Creating specific type of array

### zeros

In [12]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### identity
- a square matrix

In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### eye
- Not necessarily a square matrix, only diagonal elements are set to `1`

In [19]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### empty
- filled with random data

In [25]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Transposing an Array

In [28]:
a = np.random.randint(1,20,12).reshape(3,4)
print(a)
print(a.shape)

[[11 14  9  4]
 [18 11  4  6]
 [ 6 10  5 14]]
(3, 4)


In [29]:
b = np.transpose(a)
print(b)
print(b.shape)

[[11 18  6]
 [14 11 10]
 [ 9  4  5]
 [ 4  6 14]]
(4, 3)


In [30]:
b.T # T = transpose

array([[11, 14,  9,  4],
       [18, 11,  4,  6],
       [ 6, 10,  5, 14]])

## Modifying array values

In [31]:
a = np.random.randint(1,20,12).reshape(3,4)
a

array([[15, 14,  9, 12],
       [ 6, 14, 12, 18],
       [ 1, 18, 11, 19]])

In [32]:
a[1,1]

14

In [33]:
a[1,1] = 1400
a

array([[  15,   14,    9,   12],
       [   6, 1400,   12,   18],
       [   1,   18,   11,   19]])

## Spliting an array

### hsplit --> Left to right columns

In [34]:
a = np.random.randint(1,20,12).reshape(3,4)
a

array([[17,  9,  3, 11],
       [ 7,  8, 18,  6],
       [15, 14,  1, 11]])

In [37]:
np.hsplit(a,2)

[array([[17,  9],
        [ 7,  8],
        [15, 14]]),
 array([[ 3, 11],
        [18,  6],
        [ 1, 11]])]

In [38]:
a = np.random.randint(1,20,12).reshape(4,3)
a

array([[14, 11,  8],
       [13,  3, 11],
       [ 2, 11,  3],
       [ 6, 10, 10]])

In [40]:
# np.hsplit(a,2)

### vsplit --> Top to Bottom rows

In [38]:
a = np.random.randint(1,20,12).reshape(4,3)
a

array([[14, 11,  8],
       [13,  3, 11],
       [ 2, 11,  3],
       [ 6, 10, 10]])

In [41]:
np.vsplit(a,2)

[array([[14, 11,  8],
        [13,  3, 11]]),
 array([[ 2, 11,  3],
        [ 6, 10, 10]])]

In [42]:
a = np.random.randint(1,20,12).reshape(3,4)
a

array([[14,  8,  8, 16],
       [11, 12,  3, 15],
       [ 9, 13,  6, 18]])

In [44]:
# np.vsplit(a,2)

## Stacking up arrays

In [45]:
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### hstack --> Left to right columns

In [47]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### vstack --> Top to Bottom columns

In [48]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Flattening an array

## Repeat and tile

### repeat

### tile

## Append, Insert, Concatenate

### Append
- Append values to the end of an array.

### Insert
- Insert values along the given axis before the given indices.

### Concatenate
- Join a sequence of arrays along an existing axis.

## Arithmetic Operation on array

## Indexing and Slicing
- array[row_num, col_num,step]

## Statistical functions

### min,max,argmin,argmax,amin,amix

### Using axis

### mean,median,std,var

### ptp

### percentile

### Histogram

## Conditional functions

### using where

###### or

### using nonzero

### ptp

### percentile

### using extract

## shallow copy and Deep copy

### shallow copy : modifying array 'b' will be reflected in array `a` as well

### deep copy : modifying array 'b' will `NOT` be reflected in array `a`

## Arithmetic Operation on array

## Linear Algebra

### dot product

### eigen values and eigen vectors

### determinant

### inverse of a matrix
- The inverse of a matrix means, if it is multiplied by the original matrix, it results in identity matrix.

## Ploynomial equation

## Get sin/cos values and plot them

## Input/Output in numpy

### saving in binary format

### saving in binary format

## finding null, non-null, nan values in array

## How to find total number of null values

# Interview Questions