# Introduction to Pandas

In [16]:
import numpy as np
import pandas as pd

In [2]:
print(pd.__version__)

1.3.2


In [3]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'con

# - Pandas Series

### empty series

In [4]:
s = pd.Series()
s

/var/folders/dt/34mh0kcs6vb1yfxmbqn51tm00000gp/T/ipykernel_2951/3032608601.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


Series([], dtype: float64)

### series with list/tuple data

In [5]:
l = [1,2,3,4]
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
l = (1,2,3,4)
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
l = (1,2,3,"4")
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: object

### series using numpy array

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
s = pd.Series(a)
s

0    1
1    2
2    3
3    4
dtype: int64

### series using dictionary

In [10]:
d = {'A':1,"B":2,"C":3}
print(d)

{'A': 1, 'B': 2, 'C': 3}


In [11]:
s = pd.Series(d)
s

A    1
B    2
C    3
dtype: int64

### series using index names

In [12]:
l = [1,2,3,4]
s = pd.Series(l,index=["A","B","C","D"])
s

A    1
B    2
C    3
D    4
dtype: int64

In [13]:
# l = [1,2,3,4]
# s = pd.Series(l,index=["A","B","C"])
# s

In [14]:
# l = [1,2,3,4]
# s = pd.Series(l,index=["A","B","C","D","E"])
# s

In [15]:
# l = [1]
# s = pd.Series(l,index=["A","B"])
# s

### series with scalar values

In [16]:
l = 40
s = pd.Series(l,index=["A","B","C"])
s

A    40
B    40
C    40
dtype: int64

In [17]:
l = 40
s = pd.Series(l,index=["A","B","C"],dtype="int8")
s

A    40
B    40
C    40
dtype: int8

## Indexing/Slicing for Series

In [18]:
a = [10,20,30,40,50]
s = pd.Series(a)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [19]:
s[0]

10

In [20]:
s[3]

40

In [21]:
a = [10,20,30,40,50]
s = pd.Series(a,index=list("ABCDE"))
s

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [22]:
s["A"]

10

In [23]:
s[0]

10

In [24]:
s[["A","C","D"]]

A    10
C    30
D    40
dtype: int64

In [25]:
s[2:]

C    30
D    40
E    50
dtype: int64

In [26]:
s[2:4]

C    30
D    40
dtype: int64

In [27]:
s["A":]

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [28]:
s["A":'D']

A    10
B    20
C    30
D    40
dtype: int64

# Data Frames

## Empty DataFrame

In [29]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## Using Default option to create DataFrame

In [30]:
df = pd.DataFrame([1,2,3])
df

0
0  1
1  2
2  3

## DataFrame using List/Tuple

In [31]:
a = [1,2,3,4]
df = pd.DataFrame(a)
df

0
0  1
1  2
2  3
3  4

## DataFrame using numpy array

In [32]:
a = np.random.randint(1,10,15).reshape(5,3)
a

array([[1, 9, 2],
       [7, 2, 1],
       [9, 5, 6],
       [1, 2, 7],
       [1, 1, 2]])

In [33]:
df = pd.DataFrame(a)
df

0  1  2
0  1  9  2
1  7  2  1
2  9  5  6
3  1  2  7
4  1  1  2

In [34]:
df = pd.DataFrame(a,columns=list("ABC"))
df

A  B  C
0  1  9  2
1  7  2  1
2  9  5  6
3  1  2  7
4  1  1  2

## DataFrame using Dictionary

In [35]:
d = {"A":1,"B":2,"C":3}
df = pd.DataFrame(d,index=[100,101,102])
df

A  B  C
100  1  2  3
101  1  2  3
102  1  2  3

## Attributes and Methods of a DataFrame

In [36]:
a = np.random.randint(1,20,30).reshape(5,6)
a

array([[14,  5, 14, 13,  7, 16],
       [ 6,  1, 10, 10,  8,  7],
       [ 8,  3,  1, 18, 18,  2],
       [ 6, 16, 15,  2, 11,  6],
       [ 2, 10,  4, 18,  5, 12]])

In [37]:
df = pd.DataFrame(a,columns=list("ABCDEF"))
df

A   B   C   D   E   F
0  14   5  14  13   7  16
1   6   1  10  10   8   7
2   8   3   1  18  18   2
3   6  16  15   2  11   6
4   2  10   4  18   5  12

In [38]:
print(df.dtypes)
print(df.size)
print(df.values)
print(df.shape)
print(df.items())
print(df.index)
print(df.columns)
print(df.keys())

A    int64
B    int64
C    int64
D    int64
E    int64
F    int64
dtype: object
30
[[14  5 14 13  7 16]
 [ 6  1 10 10  8  7]
 [ 8  3  1 18 18  2]
 [ 6 16 15  2 11  6]
 [ 2 10  4 18  5 12]]
(5, 6)
<generator object DataFrame.items at 0x7f9bae4f7120>
RangeIndex(start=0, stop=5, step=1)
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [39]:
df.describe() # gives summary of complete Table data

A          B          C          D          E          F
count   5.00000   5.000000   5.000000   5.000000   5.000000   5.000000
mean    7.20000   7.000000   8.800000  12.200000   9.800000   8.600000
std     4.38178   6.041523   6.140033   6.648308   5.069517   5.458938
min     2.00000   1.000000   1.000000   2.000000   5.000000   2.000000
25%     6.00000   3.000000   4.000000  10.000000   7.000000   6.000000
50%     6.00000   5.000000  10.000000  13.000000   8.000000   7.000000
75%     8.00000  10.000000  14.000000  18.000000  11.000000  12.000000
max    14.00000  16.000000  15.000000  18.000000  18.000000  16.000000

## setting name for rows and columns

In [40]:
df

A   B   C   D   E   F
0  14   5  14  13   7  16
1   6   1  10  10   8   7
2   8   3   1  18  18   2
3   6  16  15   2  11   6
4   2  10   4  18   5  12

In [41]:
print(df)
print(df.rename(index={1:100,4:"B"},columns={"A":"ABC","D":"DEF"}))
print(df)

    A   B   C   D   E   F
0  14   5  14  13   7  16
1   6   1  10  10   8   7
2   8   3   1  18  18   2
3   6  16  15   2  11   6
4   2  10   4  18   5  12
     ABC   B   C  DEF   E   F
0     14   5  14   13   7  16
100    6   1  10   10   8   7
2      8   3   1   18  18   2
3      6  16  15    2  11   6
B      2  10   4   18   5  12
    A   B   C   D   E   F
0  14   5  14  13   7  16
1   6   1  10  10   8   7
2   8   3   1  18  18   2
3   6  16  15   2  11   6
4   2  10   4  18   5  12


In [42]:
print(df)
print(df.rename(index={1:100,4:"B"},columns={"A":"ABC","D":"DEF"},inplace=True))
print(df)

    A   B   C   D   E   F
0  14   5  14  13   7  16
1   6   1  10  10   8   7
2   8   3   1  18  18   2
3   6  16  15   2  11   6
4   2  10   4  18   5  12
None
     ABC   B   C  DEF   E   F
0     14   5  14   13   7  16
100    6   1  10   10   8   7
2      8   3   1   18  18   2
3      6  16  15    2  11   6
B      2  10   4   18   5  12


## Indexing/Slicing for Series

In [43]:
a = np.random.randint(1,20,30).reshape(5,6)
df = pd.DataFrame(a,columns=list("ABCDEF"))
df

A   B   C   D   E   F
0   7   5  10  14   1   5
1  18   9  11   7  12   4
2   2   2  14  17   5  13
3   8   7  10   5   1  19
4   7  14   8   4  17  14

## using `[]` notation

In [44]:
df["A"]

0     7
1    18
2     2
3     8
4     7
Name: A, dtype: int64

In [45]:
df[["A","C"]]

A   C
0   7  10
1  18  11
2   2  14
3   8  10
4   7   8

In [46]:
df[["A","C"]]

A   C
0   7  10
1  18  11
2   2  14
3   8  10
4   7   8

## using `.` notation

In [47]:
df.A

0     7
1    18
2     2
3     8
4     7
Name: A, dtype: int64

### using loc()

In [48]:
# <DataFrame>.loc[<row_index_name>,<col_header_name>]

In [49]:
df.loc[0,"A"]

7

In [50]:
df.loc[0,["A","D"]]

A     7
D    14
Name: 0, dtype: int64

In [51]:
df.loc[0:,["A","D"]]

A   D
0   7  14
1  18   7
2   2  17
3   8   5
4   7   4

In [52]:
df.loc[[0,4,3],["A","D"]]

A   D
0  7  14
4  7   4
3  8   5

In [53]:
df.loc[[0,4,3],"A":]

A   B   C   D   E   F
0  7   5  10  14   1   5
4  7  14   8   4  17  14
3  8   7  10   5   1  19

### using iloc()

In [54]:
df

A   B   C   D   E   F
0   7   5  10  14   1   5
1  18   9  11   7  12   4
2   2   2  14  17   5  13
3   8   7  10   5   1  19
4   7  14   8   4  17  14

In [55]:
df.iloc[0,0]

7

In [56]:
# df.iloc[0,"A"]

In [57]:
df.iloc[0,2:5]

C    10
D    14
E     1
Name: 0, dtype: int64

In [58]:
df.iloc[::-1,::-1]

F   E   D   C   B   A
4  14  17   4   8  14   7
3  19   1   5  10   7   8
2  13   5  17  14   2   2
1   4  12   7  11   9  18
0   5   1  14  10   5   7

## To Transpose DataFrame

In [59]:
df.T

0   1   2   3   4
A   7  18   2   8   7
B   5   9   2   7  14
C  10  11  14  10   8
D  14   7  17   5   4
E   1  12   5   1  17
F   5   4  13  19  14

# Slicing for Data Frames

In [60]:
df.iloc[::-1,::-1]

F   E   D   C   B   A
4  14  17   4   8  14   7
3  19   1   5  10   7   8
2  13   5  17  14   2   2
1   4  12   7  11   9  18
0   5   1  14  10   5   7

In [61]:
df.iloc[1:5:2,:4:3]

A  D
1  18  7
3   8  5

PART-2

# How to see top rows and bottom rows of a DataFrame

In [323]:
import numpy as np
import pandas as pd

In [327]:
a = np.random.randint(1,50,90).reshape(30,3)
df = pd.DataFrame(a,columns=list("ABC"))
df

A   B   C
0   20  49   6
1   37  49   9
2   31  15  21
3    6  19  45
4   25   9  31
5   22  44  13
6   36  34  11
7   37   5  49
8   10  23  48
9   45  11   5
10  15  37  23
11  19  27  14
12  32   9  36
13   4  30  18
14  38  42  16
15   2   8  41
16   8  32  23
17  46   6  39
18  39  34  31
19  48  43  13
20  46  48  36
21  21  46  39
22   2  47  47
23   2  44  23
24  27  11  46
25  16  41  42
26  36  41  45
27  45  17   1
28  23  29  40
29  24  38  48

In [328]:
df.head()

A   B   C
0  20  49   6
1  37  49   9
2  31  15  21
3   6  19  45
4  25   9  31

In [330]:
df.head(2)

A   B  C
0  20  49  6
1  37  49  9

In [329]:
df.tail()

A   B   C
25  16  41  42
26  36  41  45
27  45  17   1
28  23  29  40
29  24  38  48

In [331]:
df.tail(2)

A   B   C
28  23  29  40
29  24  38  48

# Setting options for DataFrame visualization

In [334]:
pd.get_option("display.max_rows")

60

In [335]:
pd.get_option("display.max_columns")

30

In [340]:
pd.set_option("display.max_rows",5)

In [338]:
pd.get_option("display.max_rows")

10

In [341]:
df

A   B   C
0   20  49   6
1   37  49   9
..  ..  ..  ..
28  23  29  40
29  24  38  48

[30 rows x 3 columns]

# - Basic Operations With Data frame

In [344]:
a = np.random.randint(1,50,25).reshape(5,5)
df = pd.DataFrame(a,columns=list("ABCDE"))
df

A   B   C   D   E
0  47  20  16  38  47
1  48  49  44   3  47
2  21  22  48  37   9
3  27  42   2  42  15
4  16  33  48  24  32

## Renaming Columns

In [346]:
df1 = df.rename(columns={"A":"Name"})
df1

Name   B   C   D   E
0    47  20  16  38  47
1    48  49  44   3  47
2    21  22  48  37   9
3    27  42   2  42  15
4    16  33  48  24  32

In [348]:
df1 = df.rename(index={0:"ROW_1",1:"ROW_2"})
df1

A   B   C   D   E
ROW_1  47  20  16  38  47
ROW_2  48  49  44   3  47
2      21  22  48  37   9
3      27  42   2  42  15
4      16  33  48  24  32

In [349]:
df1 = df.rename(index={0:"ROW_1",1:"ROW_2"},columns={"A":"Name_1","B":"Name_2"})
df1

Name_1  Name_2   C   D   E
ROW_1      47      20  16  38  47
ROW_2      48      49  44   3  47
2          21      22  48  37   9
3          27      42   2  42  15
4          16      33  48  24  32

## adding columns in DataFrame

In [350]:
df

A   B   C   D   E
0  47  20  16  38  47
1  48  49  44   3  47
2  21  22  48  37   9
3  27  42   2  42  15
4  16  33  48  24  32

In [351]:
df["Z"] = 100
df

A   B   C   D   E    Z
0  47  20  16  38  47  100
1  48  49  44   3  47  100
2  21  22  48  37   9  100
3  27  42   2  42  15  100
4  16  33  48  24  32  100

In [355]:
# df["X"] = [100]
# df

In [356]:
df["X"] = [100,200,300,400,500]
df

A   B   C   D   E    Z    X
0  47  20  16  38  47  100  100
1  48  49  44   3  47  100  200
2  21  22  48  37   9  100  300
3  27  42   2  42  15  100  400
4  16  33  48  24  32  100  500

## adding rows in DataFrame

In [357]:
df

A   B   C   D   E    Z    X
0  47  20  16  38  47  100  100
1  48  49  44   3  47  100  200
2  21  22  48  37   9  100  300
3  27  42   2  42  15  100  400
4  16  33  48  24  32  100  500

In [358]:
df.loc["row_1"] = -10
df

A   B   C   D   E    Z    X
0      47  20  16  38  47  100  100
1      48  49  44   3  47  100  200
...    ..  ..  ..  ..  ..  ...  ...
4      16  33  48  24  32  100  500
row_1 -10 -10 -10 -10 -10  -10  -10

[6 rows x 7 columns]

In [361]:
df.loc["row_1"] = [-10,-20,-30,-40,50,-60,70]
df

A   B   C   D   E    Z    X
0      47  20  16  38  47  100  100
1      48  49  44   3  47  100  200
...    ..  ..  ..  ..  ..  ...  ...
row_1 -10 -20 -30 -40  50  -60   70
row_2 -10 -20 -30 -40  50  -60  -70

[7 rows x 7 columns]

In [362]:
df.loc["row_2"] = [-10,-20,-30,-40,50,-60,-70]
df

A   B   C   D   E    Z    X
0      47  20  16  38  47  100  100
1      48  49  44   3  47  100  200
...    ..  ..  ..  ..  ..  ...  ...
row_1 -10 -20 -30 -40  50  -60   70
row_2 -10 -20 -30 -40  50  -60  -70

[7 rows x 7 columns]

## filtering data from a data frame. 

In [363]:
df

A   B   C   D   E    Z    X
0      47  20  16  38  47  100  100
1      48  49  44   3  47  100  200
...    ..  ..  ..  ..  ..  ...  ...
row_1 -10 -20 -30 -40  50  -60   70
row_2 -10 -20 -30 -40  50  -60  -70

[7 rows x 7 columns]

### using conditions for elements

In [364]:
df[df>20] # NaN = Not a Number

A     B     C     D     E      Z      X
0      47.0   NaN   NaN  38.0  47.0  100.0  100.0
1      48.0  49.0  44.0   NaN  47.0  100.0  200.0
...     ...   ...   ...   ...   ...    ...    ...
row_1   NaN   NaN   NaN   NaN  50.0    NaN   70.0
row_2   NaN   NaN   NaN   NaN  50.0    NaN    NaN

[7 rows x 7 columns]

In [365]:
df>20 # NaN = Not a Number

A      B      C      D     E      Z      X
0       True  False  False   True  True   True   True
1       True   True   True  False  True   True   True
...      ...    ...    ...    ...   ...    ...    ...
row_1  False  False  False  False  True  False   True
row_2  False  False  False  False  True  False  False

[7 rows x 7 columns]

In [366]:
df.where(df>20)

A     B     C     D     E      Z      X
0      47.0   NaN   NaN  38.0  47.0  100.0  100.0
1      48.0  49.0  44.0   NaN  47.0  100.0  200.0
...     ...   ...   ...   ...   ...    ...    ...
row_1   NaN   NaN   NaN   NaN  50.0    NaN   70.0
row_2   NaN   NaN   NaN   NaN  50.0    NaN    NaN

[7 rows x 7 columns]

### using filter() for Index and Column labels

In [369]:
df.filter("XAB")

X   A   B
0      100  47  20
1      200  48  49
...    ...  ..  ..
row_1   70 -10 -20
row_2  -70 -10 -20

[7 rows x 3 columns]

In [370]:
df.filter("row")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, row_1, row_2]

[7 rows x 0 columns]

In [371]:
df.filter(["A","C"])

A   C
0      47  16
1      48  44
...    ..  ..
row_1 -10 -30
row_2 -10 -30

[7 rows x 2 columns]

In [373]:
df.filter("row",axis=0)

Empty DataFrame
Columns: [A, B, C, D, E, Z, X]
Index: []

In [375]:
df.filter("row",axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, row_1, row_2]

[7 rows x 0 columns]

In [380]:
df = pd.DataFrame({"one":10,"two":20,"bbisyz":30,"bb1syz":30},index=["row_1","ROW_2","row_3"])
df

one  two  bbisyz  bb1syz
row_1   10   20      30      30
ROW_2   10   20      30      30
row_3   10   20      30      30

In [384]:
df.filter(regex="bb[i1]|ROW")

bbisyz  bb1syz
row_1      30      30
ROW_2      30      30
row_3      30      30

In [391]:
df.filter(regex="ROW",axis=0)

one  two  bbisyz  bb1syz
ROW_2   10   20      30      30

## Difference between `Size` and `Count()`

In [394]:
a = np.random.randint(1,30,25).reshape(5,5)
df = pd.DataFrame(a,columns=list("ABCDE"))
df

A   B   C   D   E
0  13  29  29   8  15
1  14   1  25   2  20
2   3  20   6  16   9
3   2  20  25  16  26
4  15  27  21   9   7

In [397]:
df.loc[3,"B"] = np.nan # to set NaN in dataFrame
df.loc[0,"E"] = np.nan
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [401]:
df.size # This will count total number of Entries in DataFrame including NaN

25

In [400]:
df.count() # counts only NON-NULL values

A    5
B    4
C    5
D    5
E    4
dtype: int64

# Descriptive Statistics

In [402]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

## min()

In [403]:
df.min()

A    2.0
B    1.0
C    6.0
D    2.0
E    7.0
dtype: float64

In [404]:
df.min(skipna=False)

A    2.0
B    NaN
C    6.0
D    2.0
E    NaN
dtype: float64

## max()

In [405]:
df.max()

A    15.0
B    29.0
C    29.0
D    16.0
E    26.0
dtype: float64

In [406]:
df.max(axis=1)

0    29.0
1    25.0
2    20.0
3    26.0
4    27.0
dtype: float64

## count()

In [407]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [408]:
df.A.count()

5

In [409]:
df["A"].count()

5

## mean()

In [410]:
df.mean()

A     9.40
B    19.25
C    21.20
D    10.20
E    15.50
dtype: float64

In [411]:
df.A.mean()

9.4

## median()

In [412]:
df.median()

A    13.0
B    23.5
C    25.0
D     9.0
E    14.5
dtype: float64

## std()

In [413]:
df.std()

A     6.348228
B    12.763881
C     8.955445
D     5.932959
E     9.036961
dtype: float64

## var()

In [414]:
df.var()

A     40.300000
B    162.916667
C     80.200000
D     35.200000
E     81.666667
dtype: float64

## cov()

In [415]:
df.cov()

A           B          C          D          E
A  40.300000   -3.416667  28.400000 -33.100000 -21.000000
B  -3.416667  162.916667  -2.083333  41.083333 -93.500000
C  28.400000   -2.083333  80.200000 -28.550000  52.500000
D -33.100000   41.083333 -28.550000  35.200000  -1.166667
E -21.000000  -93.500000  52.500000  -1.166667  81.666667

## corr()

In [416]:
df.corr()

A         B         C         D         E
A  1.000000 -0.048142  0.499550 -0.878829 -0.334252
B -0.048142  1.000000 -0.016248  0.561016 -0.992829
C  0.499550 -0.016248  1.000000 -0.537338  0.643185
D -0.878829  0.561016 -0.537338  1.000000 -0.019263
E -0.334252 -0.992829  0.643185 -0.019263  1.000000

## mode()

In [419]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [418]:
df.mode()

A     B     C     D     E
0   2   1.0  25.0  16.0   7.0
1   3  20.0   NaN   NaN   9.0
2  13  27.0   NaN   NaN  20.0
3  14  29.0   NaN   NaN  26.0
4  15   NaN   NaN   NaN   NaN

## cumsum()

In [420]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [421]:
df.cumsum()

A     B    C   D     E
0  13  29.0   29   8   NaN
1  27  30.0   54  10  20.0
2  30  50.0   60  26  29.0
3  32   NaN   85  42  55.0
4  47  77.0  106  51  62.0

## df.cummin()

In [423]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [422]:
df.cummin()

A     B   C  D     E
0  13  29.0  29  8   NaN
1  13   1.0  25  2  20.0
2   3   1.0   6  2   9.0
3   2   NaN   6  2   9.0
4   2   1.0   6  2   7.0

## cumax()

In [424]:
df.cummax()

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14  29.0  29   8  20.0
2  14  29.0  29  16  20.0
3  14   NaN  29  16  26.0
4  15  29.0  29  16  26.0

## cumprod()

In [425]:
df.cumprod()

A        B        C      D        E
0     13     29.0       29      8      NaN
1    182     29.0      725     16     20.0
2    546    580.0     4350    256    180.0
3   1092      NaN   108750   4096   4680.0
4  16380  15660.0  2283750  36864  32760.0

## abs()

In [426]:
df

A     B   C   D     E
0  13  29.0  29   8   NaN
1  14   1.0  25   2  20.0
2   3  20.0   6  16   9.0
3   2   NaN  25  16  26.0
4  15  27.0  21   9   7.0

In [428]:
df.loc[0,'A'] = -100
df

A     B   C   D     E
0 -100  29.0  29   8   NaN
1   14   1.0  25   2  20.0
2    3  20.0   6  16   9.0
3    2   NaN  25  16  26.0
4   15  27.0  21   9   7.0

In [429]:
df.abs()

A     B   C   D     E
0  100  29.0  29   8   NaN
1   14   1.0  25   2  20.0
2    3  20.0   6  16   9.0
3    2   NaN  25  16  26.0
4   15  27.0  21   9   7.0

## prod()

In [430]:
df.prod()

A    -126000.0
B      15660.0
C    2283750.0
D      36864.0
E      32760.0
dtype: float64

# Dataframe transformation functions

In [436]:
a = np.random.randint(1,20,12).reshape(4,3)
df = pd.DataFrame(a,columns=list("ABC"))
df


A   B   C
0  19   2   5
1  14  12  11
2  16   2  10
3  10  13   6

## use of apply()

In [437]:
df.apply(sum)

A    59
B    29
C    32
dtype: int64

In [441]:
df.apply(sum,axis=1)

0    26
1    37
2    28
3    29
dtype: int64

## use of applymap()

In [440]:
lam = lambda x:x**2
df.applymap(lam)

A    B    C
0  361    4   25
1  196  144  121
2  256    4  100
3  100  169   36

## apply custom function

In [443]:
df

A   B   C
0  19   2   5
1  14  12  11
2  16   2  10
3  10  13   6

In [445]:
def dividebyTwo(x):
    return x//2
df.applymap(dividebyTwo)

A  B  C
0  9  1  2
1  7  6  5
2  8  1  5
3  5  6  3

In [446]:
def dividebyTwo(x):
    return x/2
df.applymap(dividebyTwo)

A    B    C
0  9.5  1.0  2.5
1  7.0  6.0  5.5
2  8.0  1.0  5.0
3  5.0  6.5  3.0

PART-3

In [23]:
a = np.random.randint(1,20,30).reshape(6,5)
df = pd.DataFrame(a,columns=list("ABCDE"))
df

A   B   C   D   E
0  14  13  16  16   1
1  18  19  15   9  19
2   6  10   2  10   5
3  19   6   6  16  19
4   5   5   2  10   2
5   1   9   9  11   1

In [24]:
df.describe()

A          B          C          D          E
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   10.500000  10.333333   8.333333  12.000000   7.833333
std     7.503333   5.125102   6.153590   3.162278   8.773065
min     1.000000   5.000000   2.000000   9.000000   1.000000
25%     5.250000   6.750000   3.000000  10.000000   1.250000
50%    10.000000   9.500000   7.500000  10.500000   3.500000
75%    17.000000  12.250000  13.500000  14.750000  15.500000
max    19.000000  19.000000  16.000000  16.000000  19.000000

# using info()

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
 4   E       6 non-null      int64
dtypes: int64(5)
memory usage: 368.0 bytes


# Dropping columns/rows and reason behind this

In [26]:
df

A   B   C   D   E
0  14  13  16  16   1
1  18  19  15   9  19
2   6  10   2  10   5
3  19   6   6  16  19
4   5   5   2  10   2
5   1   9   9  11   1

In [27]:
df.loc[1,"B"] = np.nan
df.loc[5,"E"] = np.nan
df.loc[2,"E"] = np.nan
df

A     B   C   D     E
0  14  13.0  16  16   1.0
1  18   NaN  15   9  19.0
2   6  10.0   2  10   NaN
3  19   6.0   6  16  19.0
4   5   5.0   2  10   2.0
5   1   9.0   9  11   NaN

# Replacing Values

In [31]:
df.replace(np.nan, -100000)

A         B   C   D         E
0  14      13.0  16  16       1.0
1  18 -100000.0  15   9      19.0
2   6      10.0   2  10 -100000.0
3  19       6.0   6  16      19.0
4   5       5.0   2  10       2.0
5   1       9.0   9  11 -100000.0

In [33]:
# df.replace(np.nan, -100000,inplace=True)

## for Whole data set

In [34]:
df.replace(np.nan, -100000)

A         B   C   D         E
0  14      13.0  16  16       1.0
1  18 -100000.0  15   9      19.0
2   6      10.0   2  10 -100000.0
3  19       6.0   6  16      19.0
4   5       5.0   2  10       2.0
5   1       9.0   9  11 -100000.0

## for column/feature wise

In [35]:
df.B.replace({np.nan:-20000,"test":-10000})

0       13.0
1   -20000.0
2       10.0
3        6.0
4        5.0
5        9.0
Name: B, dtype: float64

## using regex

In [36]:
df

A     B   C   D     E
0  14  13.0  16  16   1.0
1  18   NaN  15   9  19.0
2   6  10.0   2  10   NaN
3  19   6.0   6  16  19.0
4   5   5.0   2  10   2.0
5   1   9.0   9  11   NaN

In [37]:
df["F"] = "PyCSR"
df["Z"] = "PyCSR2"
df

A     B   C   D     E      F       Z
0  14  13.0  16  16   1.0  PyCSR  PyCSR2
1  18   NaN  15   9  19.0  PyCSR  PyCSR2
2   6  10.0   2  10   NaN  PyCSR  PyCSR2
3  19   6.0   6  16  19.0  PyCSR  PyCSR2
4   5   5.0   2  10   2.0  PyCSR  PyCSR2
5   1   9.0   9  11   NaN  PyCSR  PyCSR2

In [39]:
df.replace("PyCSR",-99999,regex=True)

A     B   C   D     E       F       Z
0  14  13.0  16  16   1.0  -99999  -99999
1  18   NaN  15   9  19.0  -99999  -99999
2   6  10.0   2  10   NaN  -99999  -99999
3  19   6.0   6  16  19.0  -99999  -99999
4   5   5.0   2  10   2.0  -99999  -99999
5   1   9.0   9  11   NaN  -99999  -99999

In [41]:
df.replace("\w+\d$",-99999,regex=True)

A     B   C   D     E      F       Z
0  14  13.0  16  16   1.0  PyCSR  -99999
1  18   NaN  15   9  19.0  PyCSR  -99999
2   6  10.0   2  10   NaN  PyCSR  -99999
3  19   6.0   6  16  19.0  PyCSR  -99999
4   5   5.0   2  10   2.0  PyCSR  -99999
5   1   9.0   9  11   NaN  PyCSR  -99999

# Re-indexing

In [46]:
df1 = pd.DataFrame(np.random.randint(1,20,10).reshape(5,2),columns=list("AB"))
df2 = pd.DataFrame(np.random.randint(1,20,10).reshape(5,2),columns=list("CD"))
df1

A   B
0  17  11
1  12  12
2   4  17
3   5  14
4   1  18

In [47]:
df2

C   D
0   6   6
1  13  16
2   1  11
3   8  12
4   1   7

In [57]:
index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
df = pd.DataFrame({'http_status': [200, 200, 404, 404, 301],
'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
index=index)
df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

In [58]:
new_index = ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10','Chrome']
df.reindex(new_index)

http_status  response_time
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

In [59]:
new_index = ["Opera",'Safari', 'Iceweasel', 'Comodo Dragon', 'IE10','Chrome']
df.reindex(new_index)

http_status  response_time
Opera                  NaN            NaN
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

# Handling Missing Values using `fillna()`

In [62]:
a = np.random.randint(1,10,20).reshape(5,4)
df = pd.DataFrame(a,columns=list("ABCD"))
df

A  B  C  D
0  2  1  8  8
1  9  2  3  9
2  6  7  4  2
3  6  7  3  1
4  3  2  2  1

In [63]:
df.loc[0,"D"] = np.nan
df.loc[3,"C"] = np.nan
df

A  B    C    D
0  2  1  8.0  NaN
1  9  2  3.0  9.0
2  6  7  4.0  2.0
3  6  7  NaN  1.0
4  3  2  2.0  1.0

## using some values

In [66]:
df.fillna(-9000)

A  B       C       D
0  2  1     8.0 -9000.0
1  9  2     3.0     9.0
2  6  7     4.0     2.0
3  6  7 -9000.0     1.0
4  3  2     2.0     1.0

## using statistical inference

In [67]:
df.C.fillna(df.C.mean())

0    8.00
1    3.00
2    4.00
3    4.25
4    2.00
Name: C, dtype: float64

In [68]:
df.C.fillna(df.C.median())

0    8.0
1    3.0
2    4.0
3    3.5
4    2.0
Name: C, dtype: float64

In [69]:
df.C.fillna(df.C.std())

0    8.000000
1    3.000000
2    4.000000
3    2.629956
4    2.000000
Name: C, dtype: float64

## checking missing values using various methods

In [70]:
df

A  B    C    D
0  2  1  8.0  NaN
1  9  2  3.0  9.0
2  6  7  4.0  2.0
3  6  7  NaN  1.0
4  3  2  2.0  1.0

### isnull()

In [71]:
df.isnull()

A      B      C      D
0  False  False  False   True
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4  False  False  False  False

In [72]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

### notnull()

In [73]:
df.notnull()

A     B      C      D
0  True  True   True  False
1  True  True   True   True
2  True  True   True   True
3  True  True  False   True
4  True  True   True   True

In [74]:
df.notnull().sum()

A    5
B    5
C    4
D    4
dtype: int64

### isna()

In [75]:
df.isna()

A      B      C      D
0  False  False  False   True
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4  False  False  False  False

In [76]:
df.isna().sum()

A    0
B    0
C    1
D    1
dtype: int64

# Typecasting columns values using astype()

In [77]:
df

A  B    C    D
0  2  1  8.0  NaN
1  9  2  3.0  9.0
2  6  7  4.0  2.0
3  6  7  NaN  1.0
4  3  2  2.0  1.0

In [78]:
df.A.dtype

dtype('int64')

In [84]:
df.loc[0,'A'] = "10"
df

A  B    C    D
0  10  1  8.0  NaN
1   9  2  3.0  9.0
2   6  7  4.0  2.0
3   6  7  NaN  1.0
4   3  2  2.0  1.0

In [86]:
# df.A.sum()

In [81]:
df.A.dtype

dtype('O')

In [87]:
df.A = df.A.astype("int8")
df

A  B    C    D
0  10  1  8.0  NaN
1   9  2  3.0  9.0
2   6  7  4.0  2.0
3   6  7  NaN  1.0
4   3  2  2.0  1.0

In [88]:
df.A.dtype

dtype('int8')

In [89]:
df.A.sum()

34

# Iterating over DataFrame

## iteritems()

In [90]:
df

A  B    C    D
0  10  1  8.0  NaN
1   9  2  3.0  9.0
2   6  7  4.0  2.0
3   6  7  NaN  1.0
4   3  2  2.0  1.0

In [94]:
for c,s in df.iteritems():
    print(c)
    print(s)

A
0    10
1     9
2     6
3     6
4     3
Name: A, dtype: int8
B
0    1
1    2
2    7
3    7
4    2
Name: B, dtype: int64
C
0    8.0
1    3.0
2    4.0
3    NaN
4    2.0
Name: C, dtype: float64
D
0    NaN
1    9.0
2    2.0
3    1.0
4    1.0
Name: D, dtype: float64


## iterrows()

In [98]:
for i,r in df.iterrows():
    print(i)
    print(r)    

0
A    10.0
B     1.0
C     8.0
D     NaN
Name: 0, dtype: float64
1
A    9.0
B    2.0
C    3.0
D    9.0
Name: 1, dtype: float64
2
A    6.0
B    7.0
C    4.0
D    2.0
Name: 2, dtype: float64
3
A    6.0
B    7.0
C    NaN
D    1.0
Name: 3, dtype: float64
4
A    3.0
B    2.0
C    2.0
D    1.0
Name: 4, dtype: float64


## itertuples()

In [99]:
for r in df.itertuples():
    print(r)

Pandas(Index=0, A=10, B=1, C=8.0, D=nan)
Pandas(Index=1, A=9, B=2, C=3.0, D=9.0)
Pandas(Index=2, A=6, B=7, C=4.0, D=2.0)
Pandas(Index=3, A=6, B=7, C=nan, D=1.0)
Pandas(Index=4, A=3, B=2, C=2.0, D=1.0)


# sort, join and merge operations on DataFrame

## - Sort row and column labels

In [100]:
a = np.random.randint(-5,20,10).reshape(5,2)
df = pd.DataFrame(a,columns=["A","B"])
df

A  B
0   7  3
1   4 -2
2  17  1
3   4  3
4   9  3

In [102]:
df.sort_index()

A  B
0   7  3
1   4 -2
2  17  1
3   4  3
4   9  3

In [104]:
df.sort_index(ascending=False)

A  B
4   9  3
3   4  3
2  17  1
1   4 -2
0   7  3

In [105]:
df.sort_index(ascending=False,axis=1)

B   A
0  3   7
1 -2   4
2  1  17
3  3   4
4  3   9

## - Sort row and column Values

In [106]:
df

A  B
0   7  3
1   4 -2
2  17  1
3   4  3
4   9  3

In [108]:
df.sort_values(by="A")

A  B
1   4 -2
3   4  3
0   7  3
4   9  3
2  17  1

In [109]:
df.sort_values(by="A",ascending=False)

A  B
2  17  1
4   9  3
0   7  3
1   4 -2
3   4  3

In [113]:
df.sort_values(by=0,ascending=False,axis=1)

A  B
0   7  3
1   4 -2
2  17  1
3   4  3
4   9  3

In [114]:
df.sort_values(by=0,ascending=True,axis=1)

B   A
0  3   7
1 -2   4
2  1  17
3  3   4
4  3   9

## - Merging  dataframes

## - Joining  dataframes

## Concatenating dataframes

# - Importing external data to DataFrame

## reading `CSV` file

## reading `XLSX` file

## reading xlsx file with specific sheet name/number

## reading `HTML` file

## WebScrapping and fetching Table data

# - Exporting DataFrame to external file .csv,.html etc